### PR TITLE
Allow use of sourceRoot option for source map generation

### PR DESCRIPTION
**Pull request by radium-v**
Hi,

I'm using grunt-contrib-requirejs to build my app. The issue is that the build directory sits next to the app directory. This generates sources that are relative to the `baseUrl`, which causes issues when viewing the folder structure in Chrome.

I don't know if this pull request covers all the bases, but it works for now and I'd be happy to fill in the gaps where needed to get the `sourceRoot` option to work.

### CODE REVIEW

**Comment by ymengesha** [comment]
Hi, the behavior I am seeing using this patch is the paths in the `sources` field seem to have the `sourceRoot` value prepended to them, but the `sourceRoot` field is not present in the source map. But looking at the [source code](https://github.com/jrburke/r.js/blob/master/build/jslib/source-map/source-map-generator.js#L366), the `sourceRoot` is set in the externalizing of the source-map if the it is available.
```javascript
SourceMapGenerator.prototype.toJSON =
function SourceMapGenerator_toJSON() {
  var map = {
    version: this._version,
    file: this._file,
    sources: this._sources.toArray(),
    names: this._names.toArray(),
    mappings: this._serializeMappings()
  };
  if (this._sourceRoot) {
    map.sourceRoot = this._sourceRoot;
  }
  if (this._sourcesContents) {
    map.sourcesContent = this._generateSourcesContent(map.sources, map.sourceRoot);
  }

  return map;
};
```
Do you observe the same behavior? If so, do you have any idea why this is happening?

**Comment by jrburke** [comment]
I would likely want to see the config value used by r.js to be something like `config.sourceMapRoot`, to make it clear for the r.js options what it is vs a more generic sounding sourceRoot. It would also be helpful to have a test case or at least a sketch of an example that I could turn into a test case to confirm any fix that is done is correct and does not regress in the future, and to be sure it all makes sense with the later comments on #425.

**Comment by radium-v** [comment]
It turns out this isn't necessary when using UglifyJS2 since I can pass the property directly through the config:

```json
"generateSourceMaps": true,
"optimize": "uglify2",
"uglify2": {
  "sourceRoot": "/assets/js"
}
```

**Comment by jrburke** [comment]
Closing as uglify2 can accept the sourceRoot directly.

**Pull request closed without merging**
